# Generated by Django 4.1.6 on 2023-02-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonToElasticParser', '0002_model_content_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='content_id',
        ),
    ]
